FROM python:3.11

# Update the package lists and install required dependencies
RUN apt-get update && apt-get install -y \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libu2f-udev \
    libvulkan1 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    xdg-utils \
    && rm -rf /var/lib/apt/lists/*
RUN apt -f install -y
RUN apt-get install -y wget
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get install ./google-chrome-stable_current_amd64.deb -y

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY /Services /root/Services

# Copy the main program
COPY controller.py /root/controller.py

EXPOSE 8080

WORKDIR /root

RUN mkdir uploads

CMD ["uvicorn", "controller:app", "--host", "0.0.0.0", "--port", "8000"]