FROM node:alpine

COPY package.json /root/package.json
COPY package-lock.json /root/package-lock.json
COPY /public /root/public
COPY /src /root/src

WORKDIR /root

# Install dependencies
RUN npm install

# Build the React app
RUN npm run build

# Expose port 3010
EXPOSE 3010

# Command to run the React app
CMD ["npm", "start"]