FROM node:alpine

COPY package.json /root/package.json
COPY package-lock.json /root/package-lock.json
COPY /public /root/public
COPY /src /root/src

WORKDIR /root

RUN npm install
RUN npm install react-bootstrap
RUN npm run build
EXPOSE 3010

CMD ["npm", "start"]